name: "CI Workflow"

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yaml

  playwright-tests:
    secrets: inherit
    needs: build-and-test
    uses: ./.github/workflows/playwright-tests.yaml

  sonar-analysis:
    secrets: inherit
    needs: playwright-tests
    uses: ./.github/workflows/sonarqube-analysis.yaml

  # deploy:
  # uses: ./deploy-to-cloud-run.yml
  # needs: sonar-analysis
