name: "CI Workflow"

on:
  push:
    branches:
      - "master"

jobs:
  build-and-test:
    uses: ./build-and-test.yaml

  sonar-analysis:
    uses: ./sonarqube-analysis.yaml
    needs: build-and-test

  # deploy:
    # uses: ./deploy-to-cloud-run.yml
    # needs: sonar-analysis 
