name: "CI Workflow"

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  jest-test:
    uses: ./.github/workflows/jest-test.yaml

  playwright-test:
    secrets: inherit
    needs: jest-test
    uses: ./.github/workflows/playwright-test.yaml

  sonar-analysis:
    secrets: inherit
    needs: playwright-test
    uses: ./.github/workflows/sonarqube-analysis.yaml

  # deploy:
  # uses: ./deploy-to-cloud-run.yml
  # needs: sonar-analysis
